version: '3.7'

services:

  api:
    build: ./
    container_name: api
    volumes:
      - ./internal/images:/build/internal/images
    depends_on:
      - postgresdb
    ports:
      - 4000:4000
    env_file:
      - ./.env.aws
    
    networks:
      local-api:
      server:
        ipv4_address: 172.23.0.2

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - grenades_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5439:5432
    networks:
      - local-api

  migrations:
    build: 
      dockerfile: Dockerfile.migrate
    command: sh migrations.sh
    depends_on:
      - postgresdb
    networks:
      - local-api

networks:
  server:
    name: grenades-network
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
  local-api:

volumes:
  grenades_postgres_data: